webtalk_init -webtalk_dir C:/Users/shengruizhang/Desktop/DigLogic-master/lab_4/lab_4.sim/sim_1/synth/func/xsim/xsim.dir/vending_sim_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Oct 12 16:48:13 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2288692" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174115765_174115766_174417222_460" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a87e64da-6dc5-4c4c-a055-93a1dd555800" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f46409856fe749f685439526ed4d3e9b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3312 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "11 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5856_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2498414430 -regid "174115765_174115766_174417222_460" -xml C:/Users/shengruizhang/Desktop/DigLogic-master/lab_4/lab_4.sim/sim_1/synth/func/xsim/xsim.dir/vending_sim_func_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/shengruizhang/Desktop/DigLogic-master/lab_4/lab_4.sim/sim_1/synth/func/xsim/xsim.dir/vending_sim_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/shengruizhang/Desktop/DigLogic-master/lab_4/lab_4.sim/sim_1/synth/func/xsim/xsim.dir/vending_sim_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
