set_property IOSTANDARD LVCMOS33 [get_ports {inp[3]}]
set_property PACKAGE_PIN V10 [get_ports {inp[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inp[2]}]
set_property PACKAGE_PIN U11 [get_ports {inp[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inp[1]}]
set_property PACKAGE_PIN U12 [get_ports {inp[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inp[0]}]
set_property PACKAGE_PIN H6 [get_ports {inp[0]}]
##set_property PACKAGE_PIN E3 [get_ports Clk]
##set_property IOSTANDARD LVCMOS33 [get_ports Clk]

## This part is to activate or deactive ANODE of each display digit
set_property IOSTANDARD LVCMOS33 [get_ports {outp[0]}]
set_property PACKAGE_PIN L18 [get_ports {outp[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outp[1]}]
set_property PACKAGE_PIN T11 [get_ports {outp[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outp[2]}]
set_property PACKAGE_PIN P15 [get_ports {outp[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outp[3]}]
set_property PACKAGE_PIN K13 [get_ports {outp[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outp[4]}]
set_property PACKAGE_PIN K16 [get_ports {outp[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outp[5]}]
set_property PACKAGE_PIN R10 [get_ports {outp[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outp[6]}]
set_property PACKAGE_PIN T10 [get_ports {outp[6]}]
